version: '3.8'
services:
  sentimentAnalysis:
    image: sunyerim/sunjoo:sentimentAnalysis
    container_name: sunjoo-server-sentimentanalysis
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: sunjoo-sentimentanalysis.clau8wyu484y.ap-northeast-2.rds.amazonaws.com/analysis_result
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sentimentAnalysis0606
      SPRING_DATASOURCE_DRIVER_CLASS: com.mysql.cj.jdbc.Driver
