version: '3.8'
services:
  sentimentAnalysis:
    image: analysis
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8095:8095
    networks:
      - eureka-network
networks:
  eureka-network:
    driver: bridge