server:
  port: 8095
  servlet:
    context-path: /analyze

spring:
  application:
    name: sentimentAnalysis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sunjoo-sentimentanalysis.clau8wyu484y.ap-northeast-2.rds.amazonaws.com:3306/juryu?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: sentimentAnalysis0606
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 30
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://sunjoo-server-eureka-eureka-1:8761/eureka/

